version: 2

models:
  - name: course_enrollments
    description: "Enrollment mode of users in the course"
    columns:
      - name: org
        description: "Organization offering the course"
        type: string
      - name: course_key
        description: "Course key"
        type: string
      - name: actor_count
        description: "Count of users"
        type: int32
      - name: enrollment_mode
        description: "The enrollment mode of the user"
        data_tests:
          - accepted_values:
              values: ["audit", "honor", "verified"]        
        type: string
      - name: course_name
        description: "The name of the course"
        type: string
      - name: course_run
        description: "The course run identifier"
        type: string
